### ISSUE TITLE
Дополнить метод для выдачи юзеров

### ISSUE THREAD

**Issue by olegbur** [navff/mhbb-back#25]
Добавить в метод GET api/user/search?word={word}&page={page} атрибут для выдачи модераторов

**Comment by navff** [comment]
Типа &admins=true ?

**Comment by olegbur** [comment]
Да

**Comment by navff** [comment]
Сделано
http://test.mhbb.ru/b/Help/Api/GET-api-user-search_roles[0]_roles[1]_word_page

**Comment by navff** [comment]
Готово
