### ISSUE TITLE
Неактивна кнопка «Опубликовать» при добавлении организатора

### ISSUE THREAD

**Issue by navff** [navff/mhbb-back#59]
Заполнил все поля, а кнопка всё равно недоступна для нажатия:
http://easycaptures.com/fs/uploaded/1133/2368378318.jpg

**Comment by olegbur** [comment]
Реализовал. Но при отправлении null в OrganizerId, приходит: 
Message":"The request is invalid.","ModelState":{"postViewModel.OrganizerId":["Error converting value {null} to type 'System.Int32'. Path 'OrganizerId', line 18, position 21.

Нужно придумать, что показывать в тултипе при наведении на отключенные поля "город" и "трезвость", когда выбран органайзер. Предлагаю "Организатор уже выбран"

**Comment by navff** [comment]
Починено
