### ISSUE TITLE
Сделать заготовки для статических страниц 

### ISSUE THREAD

**Issue by navff** [navff/mhbb-back#62]
О проекте, 
Стать спонсором
Стать представителем

А я туда добавлю то что нужно добавить. Какой-то текст.

**Comment by navff** [comment]
Куда смотреть? Где искать в структуре проекта?

**Comment by olegbur** [comment]
Вся статика в static.component.html. там 3 блока: 
![default](https://user-images.githubusercontent.com/25739698/33649142-bb7a3f04-da6d-11e7-9e49-a900f4904a8c.jpg)
