### ISSUE TITLE
Неаффтаризованный пользователь ломает кнопочу «Оставить отзыв»

### ISSUE THREAD

**Issue by navff** [navff/mhbb-back#67]
http://easycaptures.com/fs/uploaded/1199/7188393049.jpg

Зашёл как анонимус, попробовал оставить отзыв, но ничего не получилось. 401 ошибка вызывает беспонечное колесо.

**Comment by olegbur** [comment]
Сейчас вывожу тултип, аналогичным образом поступил с голосованием
