### ISSUE TITLE
Если у организатора не заполнен Email или телефон, не давать подтвердить активность

### ISSUE THREAD

**Issue by navff** [navff/mhbb-back#68]
1. Создаём активность с новым организатором. 
2. Заходим под админом, выбираем активность и пытаемся «Подтвердить». 
3. Бэк ругается 400 ошибкой, что нужен Email и телефон организатора. 

Нужно фронту тоже красиво ругаться: «Не заполнены email или телефон организатора. Перейдите в редактирование организатора и заполните их».

http://easycaptures.com/fs/uploaded/1199/0802497117.jpg

**Comment by navff** [comment]
Фронтенд молчит. Просто не даёт подтвердить, а сообщений не показывает.

**Comment by olegbur** [comment]
Исправил. Баг был вызван изменением формата ошибки на бэке

**Comment by navff** [comment]
Во! Очень круто! Ссылочка в тему.
