### ISSUE TITLE
Для залогиненного пользователя отображается ссылка «Вход»

### ISSUE THREAD

**Issue by navff** [navff/mhbb-back#71]
http://easycaptures.com/fs/uploaded/1199/4134031209.jpg
Думаю, если я залогинен, там должна быть ссылочка «выход».

**Comment by navff** [comment]
Для админа исправлено, а для гостя — нет. http://easycaptures.com/fs/uploaded/1240/9001037848.jpg

**Comment by olegbur** [comment]
Исправил
